// this file reflects the terms defined by the RightsML Profile of ODRL
// genuine RightsML terms
// base URI: http://iptc.org/std/RightsML/2011-10-07/ ?

export const profileUrl = 'https://iptc.org/std/RightsML/odrl-profile/';

// ODRL Common Vocabulary terms adopted by IPTC for RightsML
// base URI: http://www.w3.org/ns/odrl/2/
// RightsML terms as JS constants
// A sequence of: Actions
export const acceptTracking = "http://www.w3.org/ns/odrl/2/acceptTracking";
export const aggregate = "http://www.w3.org/ns/odrl/2/aggregate";
export const annotate = "http://www.w3.org/ns/odrl/2/annotate";
export const anonymize = "http://www.w3.org/ns/odrl/2/anonymize";
export const archive = "http://iptc.org/std/RightsML/2011-10-07/archive";
export const attribute = "http://www.w3.org/ns/odrl/2/attribute";
export const compensate = "http://www.w3.org/ns/odrl/2/compensate";
export const concurrentUse = "http://www.w3.org/ns/odrl/2/concurrentUse";
export const deleteAction = "http://www.w3.org/ns/odrl/2/delete";
export const derive = "http://www.w3.org/ns/odrl/2/derive";
export const digitize = "http://www.w3.org/ns/odrl/2/digitize";
export const display = "http://www.w3.org/ns/odrl/2/display";
export const distribute = "http://www.w3.org/ns/odrl/2/distribute";
export const ensureExclusivity = "http://www.w3.org/ns/odrl/2/ensureExclusivity";
export const execute = "http://www.w3.org/ns/odrl/2/execute";
export const extract = "http://www.w3.org/ns/odrl/2/extract";
export const give = "http://www.w3.org/ns/odrl/2/give";
export const grantUse = "http://www.w3.org/ns/odrl/2/grantUse";
export const include = "http://www.w3.org/ns/odrl/2/include";
export const index = "http://www.w3.org/ns/odrl/2/index";
export const inform = "http://www.w3.org/ns/odrl/2/inform";
export const modify = "http://www.w3.org/ns/odrl/2/modify";
export const move = "http://www.w3.org/ns/odrl/2/move";
export const nextPolicy = "http://www.w3.org/ns/odrl/2/nextPolicy";
export const obtainConsent = "http://www.w3.org/ns/odrl/2/obtainConsent";
export const play = "http://www.w3.org/ns/odrl/2/play";
export const present = "http://www.w3.org/ns/odrl/2/present";
export const print = "http://www.w3.org/ns/odrl/2/print";
export const reproduce = "http://www.w3.org/ns/odrl/2/reproduce";
export const reviewPolicy = "http://www.w3.org/ns/odrl/2/reviewPolicy";
export const sell = "http://www.w3.org/ns/odrl/2/sell";
export const stream = "http://www.w3.org/ns/odrl/2/stream";
export const synchronize = "http://www.w3.org/ns/odrl/2/synchronize";
export const textToSpeech = "http://www.w3.org/ns/odrl/2/textToSpeech";
export const transform = "http://www.w3.org/ns/odrl/2/transform";
export const translate = "http://www.w3.org/ns/odrl/2/translate";
export const watermark = "http://www.w3.org/ns/odrl/2/watermark";
// A sequence of: LeftOperands
export const absolutePosition = "http://www.w3.org/ns/odrl/2/absolutePosition";
export const absoluteSize = "http://www.w3.org/ns/odrl/2/absoluteSize";
export const absoluteSpatialPosition = "http://www.w3.org/ns/odrl/2/absoluteSpatialPosition";
export const absoluteTemporalPosition = "http://www.w3.org/ns/odrl/2/absoluteTemporalPosition";
export const percentage = "http://www.w3.org/ns/odrl/2/percentage";
export const count = "http://www.w3.org/ns/odrl/2/count";
export const dateTime = "http://www.w3.org/ns/odrl/2/dateTime";
export const delayPeriod = "http://www.w3.org/ns/odrl/2/delayPeriod";
export const deliveryChannel = "http://www.w3.org/ns/odrl/2/deliveryChannel";
export const elapsedTime = "http://www.w3.org/ns/odrl/2/elapsedTime";
export const event = "http://www.w3.org/ns/odrl/2/event";
export const fileFormat = "http://www.w3.org/ns/odrl/2/fileFormat";
export const spatialCoordinates = "http://www.w3.org/ns/odrl/2/spatialCoordinates";
export const spatial = "http://www.w3.org/ns/odrl/2/spatial";
export const industry = "http://www.w3.org/ns/odrl/2/industry";
export const language = "http://www.w3.org/ns/odrl/2/language";
export const media = "http://www.w3.org/ns/odrl/2/media";
export const meteredTime = "http://www.w3.org/ns/odrl/2/meteredTime";
export const payAmount = "http://www.w3.org/ns/odrl/2/payAmount";
export const product = "http://www.w3.org/ns/odrl/2/product";
export const purpose = "http://www.w3.org/ns/odrl/2/purpose";
export const recipient = "http://www.w3.org/ns/odrl/2/recipient";
export const timeInterval = "http://www.w3.org/ns/odrl/2/timeInterval";
export const relativePosition = "http://www.w3.org/ns/odrl/2/relativePosition";
export const relativeSize = "http://www.w3.org/ns/odrl/2/relativeSize";
export const relativeSpatialPosition = "http://www.w3.org/ns/odrl/2/relativeSpatialPosition";
export const relativeTemporalPosition = "http://www.w3.org/ns/odrl/2/relativeTemporalPosition";
export const resolution = "http://www.w3.org/ns/odrl/2/resolution";
export const systemDevice = "http://www.w3.org/ns/odrl/2/systemDevice";
export const unitOfCount = "http://www.w3.org/ns/odrl/2/unitOfCount";
export const version = "http://www.w3.org/ns/odrl/2/version";
export const virtualLocation = "http://www.w3.org/ns/odrl/2/virtualLocation";
export const compensationValue = "http://iptc.org/std/RightsML/2011-10-07/compensationValue";
// A sequence of: Party Functions
export const attributedParty = "http://www.w3.org/ns/odrl/2/attributedParty";
export const compensatedParty = "http://www.w3.org/ns/odrl/2/compensatedParty";
export const compensatingParty = "http://www.w3.org/ns/odrl/2/compensatingParty";
export const consentedParty = "http://www.w3.org/ns/odrl/2/consentedParty";
export const consentingParty = "http://www.w3.org/ns/odrl/2/consentingParty";
export const informedParty = "http://www.w3.org/ns/odrl/2/informedParty";
export const informingParty = "http://www.w3.org/ns/odrl/2/informingParty";
export const trackedParty = "http://www.w3.org/ns/odrl/2/trackedParty";
export const trackingParty = "http://www.w3.org/ns/odrl/2/trackingParty";
// A sequence of: RightOperands
export const policyUsage = "http://www.w3.org/ns/odrl/2/policyUsage";
// A sequence of: Sub-Properties
export const output = "http://www.w3.org/ns/odrl/2/output";
